[package]
name = "chibi"
version = "0.1.0"
authors = ["Richard Ramsden <richard@rramsden.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
